### ISSUE TITLE
sensu-server lookup breaks compatibility when running this outside of the pancancer_launcher

### ISSUE THREAD

**Issue by denis-yuen** [ICGC-TCGA-PanCancer/monitoring-bag#6]
Instead, simply use a variable.
Ignore relevant tasks when undefined, run them when it is defined. That way, we can continue to use this playbook in other contexts (such as the old 2.0 architecture or similar)

**Comment by SolomonShorser-OICR** [comment]
Update: sensu server's name needs to include something unique, such as the host machine's IP address (*not* 127.0.0.1).
